config/routes.rb
Rails.application.routes.draw do

  root :to => "fish#world"

  resources :users 
  resources :fish, :except => [:show]

  get '/world' => "fish#world"
  resources :profiles

  resources :products do
    resources :comments
  end

  resource :session, :only => [:new, :create, :destroy]

  get '/login' => "sessions#new", :as => "login"
  get '/logout' =>"sessions#destroy", :as => "logout"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FishMap</title>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>">FishMap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <% if logged_in? %>
                    <li class="<%= 'active' if current_page?(fish_index_path) %>">
                        <%= link_to "My Fish", fish_index_path %>
                    </li>
                    <li class="<%= 'active' if current_page?(new_fish_path) %>">
                        <%= link_to "Add Fish", new_fish_path %>
                    </li>
                    <li class="<%= 'active' if current_page?(edit_profile_path(current_user)) %>">
                        <%= link_to "Edit Profile", edit_profile_path(current_user) %>
                    </li>
                    <li class="<%= 'active' if current_page?(logout_path) %>">
                        <%= link_to "Logout", logout_path %>
                    </li>
                  <% else %>
                    <li><%= link_to "Login", login_path %></li>
                  <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

  <div id="main">
    <div class="container">
      <%= content_tag(:p, notice, :class => 'alert alert-success') if notice.present? %>	
      <%= content_tag(:p, alert, :class => 'alert alert-warning') if alert.present? %>
    </div>
    <%= yield %>
  </div>
  
  <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h4>Powered By:</h4>
                        <p>
                          <a href="http://rubyonrails.org/" >Ruby on Rails 4</a><br />
                          <a href="http://maps.google.com/" >Google Maps</a>
                        </p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h4>App by Rick Kim</h4 >
                        <ul class="list-inline">
                            <li>
                                <a href="<%= @social[:twitter] %>" class="btn-social btn-outline"><i class="fa fa-3x fa-twitter"></i></a>
                                <a href="<%= @social[:github] %>" class="btn-social btn-outline"><i class="fa fa-3x fa-github"></i></a>

                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h4>Copyright &copy; <%= Time.now.strftime("%Y")  %></h4>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>