config/routes.rb
Rails.application.routes.draw do

  root :to => "fish#world"

  resources :users 
  resources :fish, :except => [:show]

  get '/world' => "fish#world"
  resources :profiles

  resources :products do
    resources :comments
  end

  resource :session, :only => [:new, :create, :destroy]

  get '/login' => "sessions#new", :as => "login"
  get '/logout' =>"sessions#destroy", :as => "logout"

end

app/models/fish.rb
class Fish < ActiveRecord::Base
	
	belongs_to :user

	mount_uploader :attachment, AttachmentUploader

	def owned_by?(owner)
		return false unless owner.is_a?(User)
		user == owner
	end

	def caught_by
		return user.profile.name
	end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :authenticate, except: [:world]
  before_action :set_fish, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /fish
  # GET /fish.json
  def index
    @fish = current_user.fish.order("caught DESC")
    @hash = make_hash(@fish)
  end

  def world
    @fish = Fish.where("created_at > ?", 1.week.ago.to_date).where(isprivate: "f")
    @hash = make_hash(@fish)
  end

  # GET /fish/1
  # GET /fish/1.json
  def show

  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = current_user.fish.new(fish_params)

    respond_to do |format|
      if @fish.save
        format.html { redirect_to fish_index_url, notice: 'Fish was successfully created.' }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to fish_index_url, notice: 'Fish was successfully updated.' }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: 'Fish was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render "destroy", :locals => {:object => @fish}}
    end
  end

  private
    #redirect user if he/she doesn't own fish
    def correct_user
      @fish = Fish.find(params[:id])
      redirect_to(root_path) unless @fish.user_id == current_user.id
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fish_params
      params.require(:fish).permit(:species, :latitude, :longitude, :caught, :size, :attachment, :isprivate, :description)
    end
end

app/helpers/fish_helper.rb
module FishHelper
	
end

app/views/fish/_form.html.erb
<%= form_for(@fish) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :species, :class => 'btn-success disabled' %><br>
    <%= f.select :species, ["Smallmouth Bass", "Largemouth Bass", "Rainbow Trout", "Brown Trout", "Salmon"], :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :isprivate, "Private?", :class => 'btn-success disabled' %><br>
    <%= f.check_box :isprivate %>
  </div>
   <div class="field">
    <%= f.label :attachment, :class => 'btn-success disabled' %>
    <%= f.file_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :size, "Size (in)", :class => 'btn-success disabled' %><br>
    <%= f.number_field :size, in: 1.0..20.0, step: 0.5  %>
  </div>
  <div class="field">
    <%= f.label :latitude, :class => 'btn-success disabled' %><br>
    <%= f.text_field :latitude, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :longitude, :class => 'btn-success disabled' %><br>
    <%= f.text_field :longitude, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :caught, :class => 'btn-success disabled' %><br>
    <%= f.datetime_select :caught %>
  </div>
  <div class="field">
    <%= f.label :description, :class => 'btn-success disabled' %><br>
    <%= f.text_area :description, rows: 2 %>
  </div>
  <div class="actions">
    <%= link_to 'Back', :back, :class => 'btn btn-primary pull-right' %>
    <%= f.submit "Submit", :class => 'btn btn-primary pull-right' %> 
  </div>
<% end %>

app/views/fish/_formedit.html.erb
<%= form_for(@fish) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :species %><br>
    <%= f.select :species, ["Smallmouth Bass", "Largemouth Bass", "Rainbow Trout", "Brown Trout", "Salmon"]%>
  </div>
  <div class="field">
    <%= f.label :isprivate, "Private?" %><br>
    <%= f.check_box :isprivate %>
  </div>
<!--    <div class="field">
    <%= f.label :attachment %>
    <%= f.file_field :attachment, required: true %>
  </div> -->
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :caught %><br>
    <%= f.datetime_select :caught %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Update Fish", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/fish/_infowindow.html.erb
<section id="infowindow">
	<div class="row">
        <div class="col-md-6">
             <a class="pull-left" href="<%= object.attachment_url %>">
				<img style="width:100px;" src="<%= object.attachment_url %>"/><br />
				<% if object.owned_by? current_user %>
					<%= link_to 'Edit', edit_fish_path(object), :class => 'btn btn-sm' %>
				<% end %>
			</a>
        </div>
        <div class="col-md-6">
        	<div class="media-body">
		    	<h4 class="media-heading">Caught By</h4>
		    	<a href="/profiles/<%=  object.user_id %>"><%=  object.caught_by %></a>
		  	</div>
		  	<div class="btn btn-xs btn-success pull-right" onclick="window.open('http://maps.google.com/maps?saddr=Current%20Location&daddr=<%= object.latitude %>,<%= object.longitude %>')">Get Directions</div>
        </div>
 	</div>
</section>

app/views/fish/destroy.js.erb
// hide row and marker once record is deleted
$( "#<%= object.id %>" ).css("display", "none");
var markerindex = $( "#<%= object.id %>" ).attr("markerindex")
handler.removeMarker(markers[markerindex]);	
markers.splice(markerindex,1);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();

app/views/fish/edit.html.erb
<section id="editfish">
    <div class="container">
        <div class="row itembg">
            <div class="col-lg-12 ">
                <h1 class="section-heading">Edit fish</h1>
                <h3 class="section-subheading text-info">Add a new fish to your creel</h3>
            </div>
        </div>
        <div class="row text-center itembg">
            <div class="col-md-8">
                <div id="map"></div>
            </div>
            <div class="col-md-4">         
				<%= render 'form' %>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
  	handler = Gmaps.build('Google');
	handler.buildMap({ internal: {id: 'map'} }, function(){

	displayOnMap(document.getElementById('fish_latitude').value, document.getElementById('fish_longitude').value) 		
	});
	 
	function displayOnMap(latitude, longitude){
	  var marker = handler.addMarker({
	    lat: latitude,
	    lng: longitude
	  },
	  {	draggable: true
	  });
	  handler.map.centerOn(marker);
	  google.maps.event.addListener(marker.getServiceObject(), 'dragend', function() {  
       		handler.map.centerOn(marker);
       		document.getElementById('fish_latitude').value = marker.getServiceObject().getPosition().lat();
	 	    document.getElementById('fish_longitude').value = marker.getServiceObject().getPosition().lng();
  	});

	};

</script>

app/views/fish/index.html.erb
<section id="indexfish">
  <div class="container">
      <div class="row itembg">
          <div class="col-lg-12 ">
              <h1 class="section-heading">Listing fish</h1>
              <h3 class="section-subheading text-info">Your catches (all-time)</h3>
          </div>
      </div>
      <div class="row text-center itembg">
          <div class="col-md-6">
              <div id="map"></div>
          </div>
          <div class="fishlist col-md-6">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Species</th>
                <th>Picture</th>
                <th>Private?</th>
                <th>Size</th>
                <th>Caught</th>
                <th>Description</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @fish.each_with_index do |fish, index| %>
                <tr id="<%= fish.id %>"  markerindex="<%= index %>">
                  <td><%= fish.species %></td>
                  <td><div class="thumbfish"><img src="<%= fish.attachment_url %>" style="height: 100%;"/></div></td>
                  <td><%= fish.isprivate %></td>
                  <td><%= fish.size %></td>
                  <td><%= time_ago_in_words(fish.caught) %> ago</td>
                  <td><%= fish.description %></td>
                  <% if fish.owned_by? current_user %>
                  <td>
                      <div class="btn-group">
                        <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li>
                            <%= link_to 'Edit', edit_fish_path(fish), :class => 'btn btn-sm' %>
                          </li>
                          <li>
                            <%= link_to 'Destroy', fish, :remote => true, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm' %>
                          </li>
                        </ul>
                      </div>
                  </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <a href="<%= new_fish_path %>" class="btn btn-lg btn-primary">New Fish</a>
          </div>
      </div>

  </div>
</section>


<script type="text/javascript">
  
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {maxZoom: 13}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);  
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

  function centerClicked(lat, lng) {
    var coords = [lat, lng];
    handler.map.centerOn(coords);
    handler.getMap().setZoom(13);
  };

  //add evt listener to rows
  <% @fish.each_with_index do |fish, index| %>
 document.getElementById("<%= fish.id %>").addEventListener("click", function() {centerClicked(<%= fish.latitude %>, <%= fish.longitude %>)});
  <% end %>

</script>

app/views/fish/new.html.erb
<section id="addfish">
    <div class="container">
        <div class="row itembg">
            <div class="col-lg-12 ">
                <h1 class="section-heading">Add fish</h1>
                <h3 class="section-subheading text-info">Add a new fish to your creel</h3>
            </div>
        </div>
        <div class="row text-center itembg">
            <div class="col-md-8">
                <div id="map"></div>
            </div>
            <div class="col-md-4">
                <%= render 'form' %>
            </div>
        </div>
    </div>

</section>

<script type="text/javascript">
  	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {zoom: 13}, internal: {id: 'map'} }, function(){

	  if(navigator.geolocation) {
	  	navigator.geolocation.getCurrentPosition(displayOnMap);
	  	navigator.geolocation.getCurrentPosition(displayinFields); 
	  } else {
	  	alert("no geolocation");
	  };
	     		
	});
	 
	function displayOnMap(position){
	  var marker = handler.addMarker({
	    lat: position.coords.latitude,
	    lng: position.coords.longitude
	  },
	  {	draggable: true
	  });
	  handler.map.centerOn(marker);
	  google.maps.event.addListener(marker.getServiceObject(), 'dragend', function() {  
       		handler.map.centerOn(marker);
       		document.getElementById('fish_latitude').value = marker.getServiceObject().getPosition().lat();
	 	    document.getElementById('fish_longitude').value = marker.getServiceObject().getPosition().lng();
  	});

	};

	function displayinFields(position){
	  document.getElementById('fish_latitude').value = position.coords.latitude;
	  document.getElementById('fish_longitude').value = position.coords.longitude;
	};

</script>

app/views/fish/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Species:</strong>
  <%= @fish.species %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @fish.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @fish.longitude %>
</p>

<p>
  <strong>Caught:</strong>
  <%= @fish.caught %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fish.description %>
</p>

<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/world.html.erb
<section id="worldfish">
  <div class="container">
    <% if session[:user_id] %>
      <div class="row itembg">
          <div class="col-lg-12 ">
              <h1 class="section-heading">Recent Catches Worldwide</h1>
              <h3 class="section-subheading text-info">(in the last week)</h3>
          </div>
      </div>
      <div class="row text-center itembg">
          <div class="col-md-12">
            <div id="map"></div>
          </div>
      </div> 
    <% else %>
      <div class="row itembg">
          <div class="col-lg-12 ">
              <h1 class="section-heading">Recent Catches Worldwide</h1>
              <h3 class="section-subheading text-info">(in the last week)</h3>
          </div>
      </div>
      <div class="row text-center itembg">
          <div class="col-md-6">
            <div id="map"></div>
          </div>
          <div class="col-md-6">
            <div class="panel panel-success">
              <div class="panel-heading">
                <span class="text sub pull-left">Release the fish!</span>
              </div>
              <span class="text-success sub"> Keep the memories!</span>
              <div class="panel-body">             
                   <img src="http://imgur.com/nDdKmmu.jpg" style="max-width:250px;" /><br />  
                   <p>
                  FishMap lets you keep track of all your catches and organize them.
                  </p>
                  <a href="<%= new_user_path %>" class="btn btn-lg btn-success">Register</a> 
              </div>
           </div>
              
              
            </div>
          </div>
      </div>
      
    <% end %>
  </div>
</section>

<script type="text/javascript">
  var toggle = 0
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {maxZoom: 13}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);  
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>
<br>